language: groovy

jdk:
  - openjdk8
  - oraclejdk8

before_install:
 - sudo add-apt-repository -y ppa:groovy-dev/grails
 - sudo apt-get update
 - sudo apt-get install -y --force-yes grails-ppa # not sure if necessary
 - sudo apt-get install -y --force-yes grails # or the grails version.

script: grails test-app
