language: groovy

jdk:
  - openjdk8
  - oraclejdk7

addons:
  apt:
    sources:
    - mongodb-upstart
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
    - mongodb-org-shell

before_install:
 - sudo add-apt-repository -y ppa:groovy-dev/grails
 - sudo apt-get update
 - sudo apt-get install -y --force-yes grails-ppa # not sure if necessary
 - sudo apt-get install -y --force-yes grails # or the grails version.

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("app", "app");'
  
script:
 - echo "Rien à exécuter voir .travis.yml"
#grails test-app
