language: groovy

sudo: false

jdk:
 - openjdk7
 - oraclejdk8

env:
 global:
  - MONGODB_VERSION=3.4.0

addons:
 apt:
  sources:
   - mongodb-upstart
   - mongodb-3.4-precise
  packages:
   - mongodb-org-server
   - mongodb-org-shell

services:
 - mongodb

before_install:
#grails installation
 - curl -s get.sdkman.io | bash
 - source "$HOME/.sdkman/bin/sdkman-init.sh"
 - content=`more ~/.sdkman/etc/config | grep -v auto_answer`; echo "$content" > ~/.sdkman/etc/config; echo "sdkman_auto_answer=true" >> ~/.sdkman/etc/config
 - sdk install grails
 - grails -version
#mongodb installation
 - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-amazon-$MONGODB_VERSION.tgz
 - tar xfz mongodb-linux-x86_64-amazon-$MONGODB_VERSION.tgz
 - export PATH=`pwd`/mongodb-linux-x86_64-amazon-$MONGODB_VERSION/bin:$PATH
 - mkdir -p data/db
 - mongod --dbpath=data/db &
 - sleep 15

before_script:
  - sleep 15
  - travis_retry "mongo task_overflow --eval 'db.addUser(\"admin\", \"admin\");'; sleep 3"
  
script:
 - echo "Rien à exécuter voir .travis.yml"
#grails test-app
